linters:
  enable:
    - govet
    - revive
    - errcheck
    - ineffassign
    - gosimple
    - staticcheck
    - gofmt

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  exclude-use-default: false
  exclude:
    - "don't use an underscore in package name"
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
    - path: tuple_gen\.go
      linters:
        - all
