// Code generated by go generate; DO NOT EDIT.
// generate command: go run ./gen/

package column

import "github.com/ClickHouse/ch-go/proto"

type Tuple2Value[T1, T2 any] struct {
	T1 T1
	T2 T2
}

type Tuple2[T1, T2 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
}

func NewTuple2[T1, T2 any](col1 ColumnOf[T1], col2 ColumnOf[T2]) *Tuple2[T1, T2] {
	return &Tuple2[T1, T2]{
		Field1: col1,
		Field2: col2,
	}
}

func (t *Tuple2[T1, T2]) Name() string { return "" }

func (t *Tuple2[T1, T2]) Len() int { return t.Field1.Len() }

func (t *Tuple2[T1, T2]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type())
}

func (t *Tuple2[T1, T2]) Append(v Tuple2Value[T1, T2]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
}

func (t *Tuple2[T1, T2]) AppendArr(v []Tuple2Value[T1, T2]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple2[T1, T2]) Row(i int) Tuple2Value[T1, T2] {
	return Tuple2Value[T1, T2]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
	}
}

func (t *Tuple2[T1, T2]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple2[T1, T2]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple3Value[T1, T2, T3 any] struct {
	T1 T1
	T2 T2
	T3 T3
}

type Tuple3[T1, T2, T3 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
	Field3 ColumnOf[T3]
}

func NewTuple3[T1, T2, T3 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3]) *Tuple3[T1, T2, T3] {
	return &Tuple3[T1, T2, T3]{
		Field1: col1,
		Field2: col2,
		Field3: col3,
	}
}

func (t *Tuple3[T1, T2, T3]) Name() string { return "" }

func (t *Tuple3[T1, T2, T3]) Len() int { return t.Field1.Len() }

func (t *Tuple3[T1, T2, T3]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type())
}

func (t *Tuple3[T1, T2, T3]) Append(v Tuple3Value[T1, T2, T3]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
}

func (t *Tuple3[T1, T2, T3]) AppendArr(v []Tuple3Value[T1, T2, T3]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple3[T1, T2, T3]) Row(i int) Tuple3Value[T1, T2, T3] {
	return Tuple3Value[T1, T2, T3]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
		T3: t.Field3.Row(i),
	}
}

func (t *Tuple3[T1, T2, T3]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple3[T1, T2, T3]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple4Value[T1, T2, T3, T4 any] struct {
	T1 T1
	T2 T2
	T3 T3
	T4 T4
}

type Tuple4[T1, T2, T3, T4 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
	Field3 ColumnOf[T3]
	Field4 ColumnOf[T4]
}

func NewTuple4[T1, T2, T3, T4 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4]) *Tuple4[T1, T2, T3, T4] {
	return &Tuple4[T1, T2, T3, T4]{
		Field1: col1,
		Field2: col2,
		Field3: col3,
		Field4: col4,
	}
}

func (t *Tuple4[T1, T2, T3, T4]) Name() string { return "" }

func (t *Tuple4[T1, T2, T3, T4]) Len() int { return t.Field1.Len() }

func (t *Tuple4[T1, T2, T3, T4]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type())
}

func (t *Tuple4[T1, T2, T3, T4]) Append(v Tuple4Value[T1, T2, T3, T4]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
}

func (t *Tuple4[T1, T2, T3, T4]) AppendArr(v []Tuple4Value[T1, T2, T3, T4]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple4[T1, T2, T3, T4]) Row(i int) Tuple4Value[T1, T2, T3, T4] {
	return Tuple4Value[T1, T2, T3, T4]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
		T3: t.Field3.Row(i),
		T4: t.Field4.Row(i),
	}
}

func (t *Tuple4[T1, T2, T3, T4]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple4[T1, T2, T3, T4]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple5Value[T1, T2, T3, T4, T5 any] struct {
	T1 T1
	T2 T2
	T3 T3
	T4 T4
	T5 T5
}

type Tuple5[T1, T2, T3, T4, T5 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
	Field3 ColumnOf[T3]
	Field4 ColumnOf[T4]
	Field5 ColumnOf[T5]
}

func NewTuple5[T1, T2, T3, T4, T5 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5]) *Tuple5[T1, T2, T3, T4, T5] {
	return &Tuple5[T1, T2, T3, T4, T5]{
		Field1: col1,
		Field2: col2,
		Field3: col3,
		Field4: col4,
		Field5: col5,
	}
}

func (t *Tuple5[T1, T2, T3, T4, T5]) Name() string { return "" }

func (t *Tuple5[T1, T2, T3, T4, T5]) Len() int { return t.Field1.Len() }

func (t *Tuple5[T1, T2, T3, T4, T5]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type())
}

func (t *Tuple5[T1, T2, T3, T4, T5]) Append(v Tuple5Value[T1, T2, T3, T4, T5]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
}

func (t *Tuple5[T1, T2, T3, T4, T5]) AppendArr(v []Tuple5Value[T1, T2, T3, T4, T5]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple5[T1, T2, T3, T4, T5]) Row(i int) Tuple5Value[T1, T2, T3, T4, T5] {
	return Tuple5Value[T1, T2, T3, T4, T5]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
		T3: t.Field3.Row(i),
		T4: t.Field4.Row(i),
		T5: t.Field5.Row(i),
	}
}

func (t *Tuple5[T1, T2, T3, T4, T5]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple5[T1, T2, T3, T4, T5]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple6Value[T1, T2, T3, T4, T5, T6 any] struct {
	T1 T1
	T2 T2
	T3 T3
	T4 T4
	T5 T5
	T6 T6
}

type Tuple6[T1, T2, T3, T4, T5, T6 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
	Field3 ColumnOf[T3]
	Field4 ColumnOf[T4]
	Field5 ColumnOf[T5]
	Field6 ColumnOf[T6]
}

func NewTuple6[T1, T2, T3, T4, T5, T6 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5], col6 ColumnOf[T6]) *Tuple6[T1, T2, T3, T4, T5, T6] {
	return &Tuple6[T1, T2, T3, T4, T5, T6]{
		Field1: col1,
		Field2: col2,
		Field3: col3,
		Field4: col4,
		Field5: col5,
		Field6: col6,
	}
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) Name() string { return "" }

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) Len() int { return t.Field1.Len() }

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type(), t.Field6.Type())
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) Append(v Tuple6Value[T1, T2, T3, T4, T5, T6]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
	t.Field6.Append(v.T6)
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) AppendArr(v []Tuple6Value[T1, T2, T3, T4, T5, T6]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) Row(i int) Tuple6Value[T1, T2, T3, T4, T5, T6] {
	return Tuple6Value[T1, T2, T3, T4, T5, T6]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
		T3: t.Field3.Row(i),
		T4: t.Field4.Row(i),
		T5: t.Field5.Row(i),
		T6: t.Field6.Row(i),
	}
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field6.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple6[T1, T2, T3, T4, T5, T6]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field6.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple7Value[T1, T2, T3, T4, T5, T6, T7 any] struct {
	T1 T1
	T2 T2
	T3 T3
	T4 T4
	T5 T5
	T6 T6
	T7 T7
}

type Tuple7[T1, T2, T3, T4, T5, T6, T7 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
	Field3 ColumnOf[T3]
	Field4 ColumnOf[T4]
	Field5 ColumnOf[T5]
	Field6 ColumnOf[T6]
	Field7 ColumnOf[T7]
}

func NewTuple7[T1, T2, T3, T4, T5, T6, T7 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5], col6 ColumnOf[T6], col7 ColumnOf[T7]) *Tuple7[T1, T2, T3, T4, T5, T6, T7] {
	return &Tuple7[T1, T2, T3, T4, T5, T6, T7]{
		Field1: col1,
		Field2: col2,
		Field3: col3,
		Field4: col4,
		Field5: col5,
		Field6: col6,
		Field7: col7,
	}
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) Name() string { return "" }

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) Len() int { return t.Field1.Len() }

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type(), t.Field6.Type(), t.Field7.Type())
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) Append(v Tuple7Value[T1, T2, T3, T4, T5, T6, T7]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
	t.Field6.Append(v.T6)
	t.Field7.Append(v.T7)
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) AppendArr(v []Tuple7Value[T1, T2, T3, T4, T5, T6, T7]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) Row(i int) Tuple7Value[T1, T2, T3, T4, T5, T6, T7] {
	return Tuple7Value[T1, T2, T3, T4, T5, T6, T7]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
		T3: t.Field3.Row(i),
		T4: t.Field4.Row(i),
		T5: t.Field5.Row(i),
		T6: t.Field6.Row(i),
		T7: t.Field7.Row(i),
	}
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field6.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field7.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple7[T1, T2, T3, T4, T5, T6, T7]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field6.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field7.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple8Value[T1, T2, T3, T4, T5, T6, T7, T8 any] struct {
	T1 T1
	T2 T2
	T3 T3
	T4 T4
	T5 T5
	T6 T6
	T7 T7
	T8 T8
}

type Tuple8[T1, T2, T3, T4, T5, T6, T7, T8 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
	Field3 ColumnOf[T3]
	Field4 ColumnOf[T4]
	Field5 ColumnOf[T5]
	Field6 ColumnOf[T6]
	Field7 ColumnOf[T7]
	Field8 ColumnOf[T8]
}

func NewTuple8[T1, T2, T3, T4, T5, T6, T7, T8 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5], col6 ColumnOf[T6], col7 ColumnOf[T7], col8 ColumnOf[T8]) *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8] {
	return &Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]{
		Field1: col1,
		Field2: col2,
		Field3: col3,
		Field4: col4,
		Field5: col5,
		Field6: col6,
		Field7: col7,
		Field8: col8,
	}
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) Name() string { return "" }

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) Len() int { return t.Field1.Len() }

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type(), t.Field6.Type(), t.Field7.Type(), t.Field8.Type())
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) Append(v Tuple8Value[T1, T2, T3, T4, T5, T6, T7, T8]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
	t.Field6.Append(v.T6)
	t.Field7.Append(v.T7)
	t.Field8.Append(v.T8)
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) AppendArr(v []Tuple8Value[T1, T2, T3, T4, T5, T6, T7, T8]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) Row(i int) Tuple8Value[T1, T2, T3, T4, T5, T6, T7, T8] {
	return Tuple8Value[T1, T2, T3, T4, T5, T6, T7, T8]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
		T3: t.Field3.Row(i),
		T4: t.Field4.Row(i),
		T5: t.Field5.Row(i),
		T6: t.Field6.Row(i),
		T7: t.Field7.Row(i),
		T8: t.Field8.Row(i),
	}
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field6.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field7.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field8.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field6.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field7.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field8.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple9Value[T1, T2, T3, T4, T5, T6, T7, T8, T9 any] struct {
	T1 T1
	T2 T2
	T3 T3
	T4 T4
	T5 T5
	T6 T6
	T7 T7
	T8 T8
	T9 T9
}

type Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9 any] struct {
	Field1 ColumnOf[T1]
	Field2 ColumnOf[T2]
	Field3 ColumnOf[T3]
	Field4 ColumnOf[T4]
	Field5 ColumnOf[T5]
	Field6 ColumnOf[T6]
	Field7 ColumnOf[T7]
	Field8 ColumnOf[T8]
	Field9 ColumnOf[T9]
}

func NewTuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5], col6 ColumnOf[T6], col7 ColumnOf[T7], col8 ColumnOf[T8], col9 ColumnOf[T9]) *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9] {
	return &Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]{
		Field1: col1,
		Field2: col2,
		Field3: col3,
		Field4: col4,
		Field5: col5,
		Field6: col6,
		Field7: col7,
		Field8: col8,
		Field9: col9,
	}
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Name() string { return "" }

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Len() int { return t.Field1.Len() }

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type(), t.Field6.Type(), t.Field7.Type(), t.Field8.Type(), t.Field9.Type())
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Append(v Tuple9Value[T1, T2, T3, T4, T5, T6, T7, T8, T9]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
	t.Field6.Append(v.T6)
	t.Field7.Append(v.T7)
	t.Field8.Append(v.T8)
	t.Field9.Append(v.T9)
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) AppendArr(v []Tuple9Value[T1, T2, T3, T4, T5, T6, T7, T8, T9]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Row(i int) Tuple9Value[T1, T2, T3, T4, T5, T6, T7, T8, T9] {
	return Tuple9Value[T1, T2, T3, T4, T5, T6, T7, T8, T9]{
		T1: t.Field1.Row(i),
		T2: t.Field2.Row(i),
		T3: t.Field3.Row(i),
		T4: t.Field4.Row(i),
		T5: t.Field5.Row(i),
		T6: t.Field6.Row(i),
		T7: t.Field7.Row(i),
		T8: t.Field8.Row(i),
		T9: t.Field9.Row(i),
	}
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field6.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field7.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field8.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field9.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field6.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field7.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field8.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field9.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple10Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any] struct {
	T1  T1
	T2  T2
	T3  T3
	T4  T4
	T5  T5
	T6  T6
	T7  T7
	T8  T8
	T9  T9
	T10 T10
}

type Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any] struct {
	Field1  ColumnOf[T1]
	Field2  ColumnOf[T2]
	Field3  ColumnOf[T3]
	Field4  ColumnOf[T4]
	Field5  ColumnOf[T5]
	Field6  ColumnOf[T6]
	Field7  ColumnOf[T7]
	Field8  ColumnOf[T8]
	Field9  ColumnOf[T9]
	Field10 ColumnOf[T10]
}

func NewTuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5], col6 ColumnOf[T6], col7 ColumnOf[T7], col8 ColumnOf[T8], col9 ColumnOf[T9], col10 ColumnOf[T10]) *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] {
	return &Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{
		Field1:  col1,
		Field2:  col2,
		Field3:  col3,
		Field4:  col4,
		Field5:  col5,
		Field6:  col6,
		Field7:  col7,
		Field8:  col8,
		Field9:  col9,
		Field10: col10,
	}
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Name() string { return "" }

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Len() int { return t.Field1.Len() }

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type(), t.Field6.Type(), t.Field7.Type(), t.Field8.Type(), t.Field9.Type(), t.Field10.Type())
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Append(v Tuple10Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
	t.Field6.Append(v.T6)
	t.Field7.Append(v.T7)
	t.Field8.Append(v.T8)
	t.Field9.Append(v.T9)
	t.Field10.Append(v.T10)
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) AppendArr(v []Tuple10Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Row(i int) Tuple10Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] {
	return Tuple10Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{
		T1:  t.Field1.Row(i),
		T2:  t.Field2.Row(i),
		T3:  t.Field3.Row(i),
		T4:  t.Field4.Row(i),
		T5:  t.Field5.Row(i),
		T6:  t.Field6.Row(i),
		T7:  t.Field7.Row(i),
		T8:  t.Field8.Row(i),
		T9:  t.Field9.Row(i),
		T10: t.Field10.Row(i),
	}
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field6.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field7.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field8.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field9.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field10.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field6.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field7.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field8.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field9.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field10.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple11Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 any] struct {
	T1  T1
	T2  T2
	T3  T3
	T4  T4
	T5  T5
	T6  T6
	T7  T7
	T8  T8
	T9  T9
	T10 T10
	T11 T11
}

type Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 any] struct {
	Field1  ColumnOf[T1]
	Field2  ColumnOf[T2]
	Field3  ColumnOf[T3]
	Field4  ColumnOf[T4]
	Field5  ColumnOf[T5]
	Field6  ColumnOf[T6]
	Field7  ColumnOf[T7]
	Field8  ColumnOf[T8]
	Field9  ColumnOf[T9]
	Field10 ColumnOf[T10]
	Field11 ColumnOf[T11]
}

func NewTuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5], col6 ColumnOf[T6], col7 ColumnOf[T7], col8 ColumnOf[T8], col9 ColumnOf[T9], col10 ColumnOf[T10], col11 ColumnOf[T11]) *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] {
	return &Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]{
		Field1:  col1,
		Field2:  col2,
		Field3:  col3,
		Field4:  col4,
		Field5:  col5,
		Field6:  col6,
		Field7:  col7,
		Field8:  col8,
		Field9:  col9,
		Field10: col10,
		Field11: col11,
	}
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Name() string { return "" }

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Len() int { return t.Field1.Len() }

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type(), t.Field6.Type(), t.Field7.Type(), t.Field8.Type(), t.Field9.Type(), t.Field10.Type(), t.Field11.Type())
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Append(v Tuple11Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
	t.Field6.Append(v.T6)
	t.Field7.Append(v.T7)
	t.Field8.Append(v.T8)
	t.Field9.Append(v.T9)
	t.Field10.Append(v.T10)
	t.Field11.Append(v.T11)
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) AppendArr(v []Tuple11Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Row(i int) Tuple11Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] {
	return Tuple11Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]{
		T1:  t.Field1.Row(i),
		T2:  t.Field2.Row(i),
		T3:  t.Field3.Row(i),
		T4:  t.Field4.Row(i),
		T5:  t.Field5.Row(i),
		T6:  t.Field6.Row(i),
		T7:  t.Field7.Row(i),
		T8:  t.Field8.Row(i),
		T9:  t.Field9.Row(i),
		T10: t.Field10.Row(i),
		T11: t.Field11.Row(i),
	}
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field6.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field7.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field8.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field9.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field10.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field11.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field6.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field7.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field8.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field9.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field10.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field11.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}

type Tuple12Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 any] struct {
	T1  T1
	T2  T2
	T3  T3
	T4  T4
	T5  T5
	T6  T6
	T7  T7
	T8  T8
	T9  T9
	T10 T10
	T11 T11
	T12 T12
}

type Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 any] struct {
	Field1  ColumnOf[T1]
	Field2  ColumnOf[T2]
	Field3  ColumnOf[T3]
	Field4  ColumnOf[T4]
	Field5  ColumnOf[T5]
	Field6  ColumnOf[T6]
	Field7  ColumnOf[T7]
	Field8  ColumnOf[T8]
	Field9  ColumnOf[T9]
	Field10 ColumnOf[T10]
	Field11 ColumnOf[T11]
	Field12 ColumnOf[T12]
}

func NewTuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 any](col1 ColumnOf[T1], col2 ColumnOf[T2], col3 ColumnOf[T3], col4 ColumnOf[T4], col5 ColumnOf[T5], col6 ColumnOf[T6], col7 ColumnOf[T7], col8 ColumnOf[T8], col9 ColumnOf[T9], col10 ColumnOf[T10], col11 ColumnOf[T11], col12 ColumnOf[T12]) *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return &Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{
		Field1:  col1,
		Field2:  col2,
		Field3:  col3,
		Field4:  col4,
		Field5:  col5,
		Field6:  col6,
		Field7:  col7,
		Field8:  col8,
		Field9:  col9,
		Field10: col10,
		Field11: col11,
		Field12: col12,
	}
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Name() string { return "" }

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Len() int { return t.Field1.Len() }

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Type() proto.ColumnType {
	return proto.ColumnTypeTuple.Sub(t.Field1.Type(), t.Field2.Type(), t.Field3.Type(), t.Field4.Type(), t.Field5.Type(), t.Field6.Type(), t.Field7.Type(), t.Field8.Type(), t.Field9.Type(), t.Field10.Type(), t.Field11.Type(), t.Field12.Type())
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Append(v Tuple12Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) {
	t.Field1.Append(v.T1)
	t.Field2.Append(v.T2)
	t.Field3.Append(v.T3)
	t.Field4.Append(v.T4)
	t.Field5.Append(v.T5)
	t.Field6.Append(v.T6)
	t.Field7.Append(v.T7)
	t.Field8.Append(v.T8)
	t.Field9.Append(v.T9)
	t.Field10.Append(v.T10)
	t.Field11.Append(v.T11)
	t.Field12.Append(v.T12)
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) AppendArr(v []Tuple12Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) {
	for _, x := range v {
		t.Append(x)
	}
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Row(i int) Tuple12Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Tuple12Value[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{
		T1:  t.Field1.Row(i),
		T2:  t.Field2.Row(i),
		T3:  t.Field3.Row(i),
		T4:  t.Field4.Row(i),
		T5:  t.Field5.Row(i),
		T6:  t.Field6.Row(i),
		T7:  t.Field7.Row(i),
		T8:  t.Field8.Row(i),
		T9:  t.Field9.Row(i),
		T10: t.Field10.Row(i),
		T11: t.Field11.Row(i),
		T12: t.Field12.Row(i),
	}
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) DecodeColumn(r *proto.Reader, rows int) error {
	if err := t.Field1.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field2.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field3.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field4.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field5.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field6.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field7.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field8.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field9.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field10.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field11.DecodeColumn(r, rows); err != nil {
		return err
	}
	if err := t.Field12.DecodeColumn(r, rows); err != nil {
		return err
	}
	return nil
}

func (t *Tuple12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) EncodeColumn(b *proto.Buffer) error {
	if err := t.Field1.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field2.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field3.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field4.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field5.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field6.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field7.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field8.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field9.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field10.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field11.EncodeColumn(b); err != nil {
		return err
	}
	if err := t.Field12.EncodeColumn(b); err != nil {
		return err
	}
	return nil
}
